### ISSUE TITLE
Problem with database.yml

### ISSUE THREAD

**Issue by gogainda** [eval/envied#12]
I not sure how to use envied properly in database.yml
For instance I have beta environment and database.yml file like this

```
beta:
  adapter: postgresql
  encoding: unicode
  database: <%= ENVied.POSTGRESQL_DATABASE %>
  host: localhost
  username: <%= ENVied.POSTGRESQL_USERNAME %>
  password: <%= ENVied.POSTGRESQL_PASSWORD %>
  pool: 5
  timeout: 5000
```

and I have Envfile like 

```
group :beta do
  # db prod credentials
  variable :POSTGRESQL_DATABASE
  variable :POSTGRESQL_USERNAME
  variable :POSTGRESQL_PASSWORD
end
```

When I run the app in development mode it fails with error undefined method `POSTGRESQL_DATABASE' for ENVied:Class, but it should not because I am not using beta properties.
What is the problem?
